// Auto-generated by OpenLane
module dynamic_noise_reduction(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input reset,
  input[15:0] x_in,
  input[15:0] alpha,
  output[15:0] y_out
);
endmodule
