// Auto-generated by OpenLane
module dynamic_noise_filter_top(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input reset,
  input spi_clk,
  input spi_sel,
  input spi_mosi,
  output spi_miso
);
endmodule
